services:
  hugo:
    image: hugomods/hugo:go-0.121.2
    volumes:
      - .:/hugo/themes/hugo-theme-techdoc
    ports:
      - 1313:1313
    working_dir: /hugo/themes/hugo-theme-techdoc/exampleSite
    command: "hugo server --bind 0.0.0.0 -wD --ignoreCache --themesDir ../.. --minify --panicOnWarning"

  node:
    image: node:lts
    volumes:
      - .:/hugo/themes/hugo-theme-techdoc
    working_dir: /hugo/themes/hugo-theme-techdoc
    environment:
      SHELL: /bin/bash
